### ISSUE TITLE
Add support in the main page table for timelines whose name doesn't start with timeline

### ISSUE THREAD

**Issue by vipulnaik** [riceissa/timelines-wiki-main-page-table#11]
Basically, things of the form `<adjective> timeline of <X>`

For instance, `Speculative timeline of future malaria events` or `Combined timeline of malaria organizations`.

For display, I'm thinking that the initial adjective can be printed at the end in parentheses, and lowercased. For instance:

`Speculative timeline of future malaria events` becomes `Future malaria events (speculative)`

**Comment by riceissa** [comment]
Actually, I realized that the real problem is that we are currently querying the MediaWiki API with `"apprefix": "Timeline of"` when getting the full list of timelines.

**Comment by riceissa** [comment]
It doesn't seem like the API allows searching for strings that appear anywhere in the title https://timelines.issarice.com/api.php?action=help&modules=query%2Ballpages so I might need to request all pages and filter the results.
