### ISSUE TITLE
Add a column into the main page table for last modification date or month

### ISSUE THREAD

**Issue by vipulnaik** [riceissa/timelines-wiki-main-page-table#3]
I would find it really useful if the timelines wiki main page table had a column for last modified month. I think this would help in a few ways:

- It would make it easier to identify timelines that haven't been modified for a while, and then select among them which timeline is "due" for an update.
- We could check more easily if the timelines we've recently been updating have been performing well. This can help us judge whether the updates we are making to timelines are having an effect on high-value pages.

**Comment by riceissa** [comment]
How do you want to calculate the last modified month? I can see a few possibilities:

* using the last edit date on the page (so even minor typo fixes can bump the date)
* using the last edit date over some byte threshold (not sure if this is easy)
* using the last payment date
* manually specifying for each page

**Comment by vipulnaik** [comment]
I'm ok with the first option, which should hopefully be simplest even if not always the right thing to do in spirit:

> using the last edit date on the page (so even minor typo fixes can bump the date)
