### ISSUE TITLE
Add a column into the main page table for principal contributor(s)

### ISSUE THREAD

**Issue by vipulnaik** [riceissa/timelines-wiki-main-page-table#4]
The goal is to make it easier to view together the timelines whose principal contributor(s) was a specific person, e.g., @riceissa and @sebastiansanchez123, or a specific set of people (e.g., @riceissa and @sebastiansanchez123).

There are a few ways we could do this:

- Judge the principal contributor(s) based on the edit history on TW
- Judge the principal contributor(s) based on who got paid on the contract work repo

**Comment by riceissa** [comment]
Using payment info seems easier (maybe sort by total amount), but this will exclude people like you who don't edit for payment.

Edit history is a little underspecified (what counts as the threshold for being a principal contributor?)

**Comment by vipulnaik** [comment]
I'm happy going with payment info. Some timelines will have no principal contributor, but I think we'll get the bulk of the most important-to-cover stuff covered.
