### ISSUE TITLE
Create summary tables of the main page table

### ISSUE THREAD

**Issue by vipulnaik** [riceissa/timelines-wiki-main-page-table#5]
I'm interested in grouped summaries such as:

- Summary of pageview counts on timelines wiki and Wikipedia based on principal contributor(s)
- Summary of pageview counts on timelines wiki and Wikipedia based on topic
- Summary of pageview counts on timelines wiki and Wikipedia based on whether the article is on Wikipedia

**Comment by riceissa** [comment]
What summary statistics do you want (e.g. just a sum of pageviews)?

I'm guessing just sorting the existing table by the appropriate column (once we add principal contributor) is inadequate, but I don't understand why.

**Comment by vipulnaik** [comment]
> e.g. just a sum of pageviews 

Yes, exactly. Sum of pageviews on TW, sum of pageviews on Wikipedia, and total number of rows.

It would be hard for me to mentally sum up dozens of rows even after the sorting capability is added. It's hard for me to sum up more than 3-4 numbers by eyeballing. I'm guessing others will have similar limitations.

**Comment by riceissa** [comment]
How do you want to treat the case where a single timeline has multiple principal contributors?

e.g. let's say Issa Rice is principal contributor on timelines A and B, and Sebastian Sanchez is principal contributor on timelines B and C.

We could do a thing where multiple authors get to "claim" a timeline and get it included into their view counts like this:

```
Issa Rice (A,B): _ views
Sebastian Sanchez (B,C): _ views
```

or each person's name could stand for timelines where they are the sole principal contributor, like this:

```
Issa Rice (A): _ views
Sebastian Sanchez (C): _ views
Issa Rice and Sebastian Sanchez (B): _ views
```

**Comment by riceissa** [comment]
Also for pageviews I'm assuming you only want the past 30-31 days (just like the current main page table).

**Comment by vipulnaik** [comment]
@riceissa Great question! How hard would it be to break out number of views to which that person was the sole principal contributor, and number of views for which that person was one of multiple principal contributors? From this level of broken-out data, we should be able to recover both the summary views you mentioned.

**Comment by riceissa** [comment]
Here's what I have so far: https://timelines.issarice.com/wiki/User:Issa/test

what I still need to do:

* [x] check if the numbers make sense
* [x] add explanations (e.g. the date window for pageviews)
