### ISSUE TITLE
Add a column for percentage increase or decrease in pageviews since last month, for monthly pageviews on timelines wiki

### ISSUE THREAD

**Issue by vipulnaik** [riceissa/timelines-wiki-main-page-table#6]
One of the most useful exercises I am going through is to compare the pageviews of various pages on timelines wiki between this month and the last. I am then bucketing the trends as negligible / slight / large increase / decrease, and then using Search Console for determining the reasons.

It would be nice if I didn't have to open two versions of the table (this month's and last month's) to carry out this comparison. I think the need to open last month's table would be eliminated if we add a column giving the percentage increase over last month (with negative percentages indicating a decrease. We can implement capping at 1000% to avoid weird overflows and noisy edge cases (so basically if last month's number was 0, and this month's is nonzero, we just show 1000%).

I also thought of just showing the additive difference from last month to this month, which might in some ways be better. On the whole I'm leaning toward showing a percentage difference. Setting aside capping, the pieces of information should be equivalent to each other; it's more about which presentation is easier to understand and which field is more helpful to sort by.

I'm open to other better ideas, and look forward to pushback on this one.

**Comment by riceissa** [comment]
I only added a percentage change column for the Google Analytics pageviews (so no equivalent column for Wikipedia pageviews), because I think that's what you care about most and because we're already at 10 columns in the table (making it feel pretty crowded), but let me know if you also want a column for percentage change of Wikipedia pageviews.
